name: MLOps Pipeline

on:
  push:
    branches: ["main"]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dagger CLI
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | sh
          sudo mv bin/dagger /usr/local/bin/dagger
          dagger version

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run Dagger workflow
        run: |
         cd dagger
         go run main.go


      - name: Upload model artifact (required!)
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: model

      - name: Upload MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlruns/

      - name: Upload model artifacts folder
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: artifacts/
